-- O Quarto Elemento — v6.0 YouTube Intelligence Foundation
-- Run this once in Supabase > SQL Editor before saving content generated by v6.0.

create extension if not exists pgcrypto;

create table if not exists public.qe_sources (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'youtube',
  provider_id text not null,
  original_url text,
  embed_url text,
  thumbnail_url text,
  title text,
  description text,
  duration text,
  published_at text,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(provider, provider_id)
);

alter table public.qe_sources enable row level security;

do $$ begin
  create policy "Public read sources" on public.qe_sources for select using (true);
exception when duplicate_object then null; end $$;

alter table public.qe_transmissions
  add column if not exists video_id text,
  add column if not exists embed_url text,
  add column if not exists source_provider text,
  add column if not exists source_url text;

create index if not exists qe_sources_provider_id_idx on public.qe_sources(provider, provider_id);
create index if not exists qe_transmissions_video_id_idx on public.qe_transmissions(video_id);
